# SwiftLint configuration for CrossPromoKit
# Swift 6, iOS 17+, SwiftUI-first

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fallthrough
  - fatal_error_message
  - file_header
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - Sources

excluded:
  - Tests
  - .build
  - DerivedData

# Rule configurations
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - en
    - ko
    - ja

type_name:
  min_length: 3
  max_length: 50

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 400

nesting:
  type_level: 2
  function_level: 3

reporter: "xcode"
